spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/trading_platform
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
